---
title: 第十一次作业

date: 2018-12-18 
lastmod: 2018-12-18 

draft: false
# toc: true
type: docs

linktitle: 第十一次作业
menu:
  course: 
    parent: 数理统计
    weight: 16
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Consider the simple linear model

$$y_i= \beta_0+\beta_1x_i+\epsilon_i,\ \epsilon_i\stackrel{iid}{\sim} N(0,\sigma^2).$$

Use the F-test method derived in the multiple linear model to test the hypothesis $H_0:\beta_1=0\ vs.\ H_1:\beta_1\neq 0$, and see whether the F-test agrees with the earlier t-test derived in the simple linear models.


---


The following table shows the monthly returns of stock in Disney, MacDonalds,
Schlumberger, and Haliburton for January through May 1998. Fit a multiple regression
to predict Disney returns from those of the other stocks. What is the
standard deviation of the residuals? What is $R^2$?

Disney | MacDonalds | Schlumberger | Haliburton |
-|-|-|-|
0.08088  | -0.01309  | -0.08463  | -0.13373 | 
0.04737  | 0.15958  | 0.02884  | 0.03616 | 
-0.04634  | 0.09966  | 0.00165  | 0.07919 | 
0.16834  | 0.03125  | 0.09571  | 0.09227 | 
-0.09082  | 0.06206  | -0.05723  | -0.13242 | 

Next, using the regression equation you have just found, carry out the predictions
for January through May of 1999 and compare to the actual data listed
below. What is the standard deviation of the prediction error? How can the comparison
with the results from 1998 be explained? Is a reasonable explanation that
the fundamental nature of the relationships changed in the one year period? (最后一问选做)

Disney | MacDonalds | Schlumberger | Haliburton | 
-|-|-|-|
0.1  | 0.02604  | 0.02695 |  0.00211 | 
0.06629  | 0.07851  | 0.02362 |  -0.04 | 
-0.11545  | 0.06732  | 0.23938  | 0.35526 | 
0.02008  | -0.06483  | 0.06127  | 0.10714 | 
-0.08268  | -0.09029 |  -0.05773 |  -0.02933 | 


