<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 2.4.0">
  <meta name="generator" content="Hugo 0.48" />
  <meta name="author" content="Zhijian He">

  
  
  
  
    
  
  <meta name="description" content="Consider the simple linear model
\[y_i= \beta_0&#43;\beta_1x_i&#43;\epsilon_i,\ \epsilon_i\stackrel{iid}{\sim} N(0,\sigma^2).\]
Use the F-test method derived in the multiple linear model to test the hypothesis \(H_0:\beta_1=0\ vs.\ H_1:\beta_1\neq 0\), and see whether the F-test agrees with the earlier t-test derived in the simple linear models.
Solution: The F test statistic is given by
\[F = \frac{S_R^2/(p-1)}{S_e^2/(n-p)}=\frac{S_R^2}{S_e^2/(n-p)},\]
where
\[S_R^2=\sum_{i=1}^n(\hat y_i-\bar y)^2=\sum_{i=1}^n(\hat\beta_0-\hat\beta_1x_i-\bar y) = \sum_{i=1}^n(\bar y-\hat\beta_1\bar x-\hat\beta_1x_i-\bar y)^2=\hat\beta_1^2\sum_{i=1}^n(x_i-\bar x)^2=\hat\beta_1^2\ell_{xx}.\]
The t test statistic is given by">

  
  <link rel="alternate" hreflang="en-us" href="/course/homework11/">

  


  

  
  
  
  <meta name="theme-color" content="#0095eb">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css" crossorigin="anonymous">
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700%7cRoboto:400,400italic,700%7cRoboto&#43;Mono">
  

  <link rel="stylesheet" href="/styles.css">
  

  
  
  

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Dr. Zhijian He">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Dr. Zhijian He">
  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/course/homework11/">

  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="og:site_name" content="Dr. Zhijian He">
  <meta property="og:url" content="/course/homework11/">
  <meta property="og:title" content="第十一次作业 | Dr. Zhijian He">
  <meta property="og:description" content="Consider the simple linear model
\[y_i= \beta_0&#43;\beta_1x_i&#43;\epsilon_i,\ \epsilon_i\stackrel{iid}{\sim} N(0,\sigma^2).\]
Use the F-test method derived in the multiple linear model to test the hypothesis \(H_0:\beta_1=0\ vs.\ H_1:\beta_1\neq 0\), and see whether the F-test agrees with the earlier t-test derived in the simple linear models.
Solution: The F test statistic is given by
\[F = \frac{S_R^2/(p-1)}{S_e^2/(n-p)}=\frac{S_R^2}{S_e^2/(n-p)},\]
where
\[S_R^2=\sum_{i=1}^n(\hat y_i-\bar y)^2=\sum_{i=1}^n(\hat\beta_0-\hat\beta_1x_i-\bar y) = \sum_{i=1}^n(\bar y-\hat\beta_1\bar x-\hat\beta_1x_i-\bar y)^2=\hat\beta_1^2\sum_{i=1}^n(x_i-\bar x)^2=\hat\beta_1^2\ell_{xx}.\]
The t test statistic is given by">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2018-12-18T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2018-12-18T00:00:00&#43;00:00">
  

  

  

  <title>第十一次作业 | Dr. Zhijian He</title>

</head>
<body id="top" data-spy="scroll" data-target="#toc" data-offset="71" >

<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/">Dr. Zhijian He</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/post">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#publications_selected">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/talk">
            
            <span>Talks</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/course/">
            
            <span>Courses</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="/#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        
      

      
      </ul>

    </div>
  </div>
</nav>



<div class="container-fluid docs">
  <div class="row flex-xl-nowrap">
    <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
      





<form class="docs-search d-flex align-items-center">
  <input name="q" type="search" class="form-control" id="search-query" placeholder="Search..." autocomplete="off">
</form>


<nav class="docs-links" id="docs-nav">
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/course/">Overview</a>

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/course/chap00/">数理统计</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/course/chap00/">课程简介</a>
      </li>
      
      <li >
        <a href="/course/chap01/">第一章</a>
      </li>
      
      <li >
        <a href="/course/chap02/">第二章</a>
      </li>
      
      <li >
        <a href="/course/chap03/">第三章</a>
      </li>
      
      <li >
        <a href="/course/chap04/">第四章</a>
      </li>
      
      <li >
        <a href="/course/homework1/">第一次作业</a>
      </li>
      
      <li >
        <a href="/course/homework2/">第二次作业</a>
      </li>
      
      <li >
        <a href="/course/homework3/">第三次作业</a>
      </li>
      
      <li >
        <a href="/course/homework4/">第四次作业</a>
      </li>
      
      <li >
        <a href="/course/homework5/">第五次作业</a>
      </li>
      
      <li >
        <a href="/course/homework6/">第六次作业</a>
      </li>
      
      <li >
        <a href="/course/homework7/">第七次作业</a>
      </li>
      
      <li >
        <a href="/course/homework8/">第八次作业</a>
      </li>
      
      <li >
        <a href="/course/homework9/">第九次作业</a>
      </li>
      
      <li >
        <a href="/course/homework10/">第十次作业</a>
      </li>
      
      <li class="active">
        <a href="/course/homework11/">第十一次作业</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

    </div>

    

    <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">
      <div id="search-hits">
        
      </div>
      <article class="article" itemscope itemtype="http://schema.org/Article">

        


        <div class="docs-article-container">
          <h1 itemprop="name">第十一次作业</h1>

          <div class="article-style" itemprop="articleBody">
            <p>Consider the simple linear model</p>
<p><span class="math display">\[y_i= \beta_0+\beta_1x_i+\epsilon_i,\ \epsilon_i\stackrel{iid}{\sim} N(0,\sigma^2).\]</span></p>
<p>Use the F-test method derived in the multiple linear model to test the hypothesis <span class="math inline">\(H_0:\beta_1=0\ vs.\ H_1:\beta_1\neq 0\)</span>, and see whether the F-test agrees with the earlier t-test derived in the simple linear models.</p>
<p><code>Solution</code>: The F test statistic is given by</p>
<p><span class="math display">\[F = \frac{S_R^2/(p-1)}{S_e^2/(n-p)}=\frac{S_R^2}{S_e^2/(n-p)},\]</span></p>
<p>where</p>
<p><span class="math display">\[S_R^2=\sum_{i=1}^n(\hat y_i-\bar y)^2=\sum_{i=1}^n(\hat\beta_0-\hat\beta_1x_i-\bar y) = \sum_{i=1}^n(\bar y-\hat\beta_1\bar x-\hat\beta_1x_i-\bar y)^2=\hat\beta_1^2\sum_{i=1}^n(x_i-\bar x)^2=\hat\beta_1^2\ell_{xx}.\]</span></p>
<p>The t test statistic is given by</p>
<p><span class="math display">\[T=\frac{\hat\beta_1}{\sqrt{\frac{S_e^2}{(n-p)\ell_{xx}}}}.\]</span></p>
<p>As a result, <span class="math inline">\(T^2=F\)</span>. Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(T\sim t(n-p)\)</span> and <span class="math inline">\(F\sim F(1,n-p)\)</span>. The rejection region for F-test is <span class="math inline">\(W_1=\{F&gt;F_{1-\alpha}(1,n-p)\}\)</span>, and the rejection region for t-test is <span class="math inline">\(W_2=\{|T|&gt;t_{1-\alpha/2}(n-p)\}\)</span>. Note that <span class="math inline">\(P(|T|&gt;t_{1-\alpha/2}(n-p)|H_0) = P(T^2&gt;t_{1-\alpha/2}(n-p)^2|H_0) =1-\alpha\)</span>. Since <span class="math inline">\(T^2\sim F(1,n-p)\)</span> under <span class="math inline">\(H_0\)</span>, we have <span class="math inline">\(t_{1-\alpha/2}(n-p)^2=F_{1-\alpha}(1,n-p)\)</span>. This implies <span class="math inline">\(W_1=W_2\)</span>, i.e., the two tests are the same.</p>
<hr />
<p>The following table shows the monthly returns of stock in Disney, MacDonalds,
Schlumberger, and Haliburton for January through May 1998. Fit a multiple regression
to predict Disney returns from those of the other stocks. What is the
standard deviation of the residuals? What is <span class="math inline">\(R^2\)</span>?</p>
<table>
<thead>
<tr class="header">
<th>Disney</th>
<th>MacDonalds</th>
<th>Schlumberger</th>
<th>Haliburton</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.08088</td>
<td>-0.01309</td>
<td>-0.08463</td>
<td>-0.13373</td>
</tr>
<tr class="even">
<td>0.04737</td>
<td>0.15958</td>
<td>0.02884</td>
<td>0.03616</td>
</tr>
<tr class="odd">
<td>-0.04634</td>
<td>0.09966</td>
<td>0.00165</td>
<td>0.07919</td>
</tr>
<tr class="even">
<td>0.16834</td>
<td>0.03125</td>
<td>0.09571</td>
<td>0.09227</td>
</tr>
<tr class="odd">
<td>-0.09082</td>
<td>0.06206</td>
<td>-0.05723</td>
<td>-0.13242</td>
</tr>
</tbody>
</table>
<p>Next, using the regression equation you have just found, carry out the predictions
for January through May of 1999 and compare to the actual data listed
below. What is the standard deviation of the prediction error? How can the comparison
with the results from 1998 be explained? Is a reasonable explanation that
the fundamental nature of the relationships changed in the one year period? (最后一问选做)</p>
<table>
<thead>
<tr class="header">
<th>Disney</th>
<th>MacDonalds</th>
<th>Schlumberger</th>
<th>Haliburton</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.1</td>
<td>0.02604</td>
<td>0.02695</td>
<td>0.00211</td>
</tr>
<tr class="even">
<td>0.06629</td>
<td>0.07851</td>
<td>0.02362</td>
<td>-0.04</td>
</tr>
<tr class="odd">
<td>-0.11545</td>
<td>0.06732</td>
<td>0.23938</td>
<td>0.35526</td>
</tr>
<tr class="even">
<td>0.02008</td>
<td>-0.06483</td>
<td>0.06127</td>
<td>0.10714</td>
</tr>
<tr class="odd">
<td>-0.08268</td>
<td>-0.09029</td>
<td>-0.05773</td>
<td>-0.02933</td>
</tr>
</tbody>
</table>
<p><code>Solution</code>:</p>
<pre class="r"><code>stock=data.frame(Mac=c(-0.01309,0.15958,0.09966,0.03125,0.06206),
                 Sch=c(-0.08463,0.02884,0.00165,0.09571,-0.05723),
                 Hali=c(-0.13373,0.03616,0.07919,0.09227,-0.13242),
                Disney=c(0.08088,0.04737,-0.04634,0.16834,-0.09082))
lm.stock = lm(Disney~Mac+Sch+Hali,data=stock)
summary(lm.stock)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Disney ~ Mac + Sch + Hali, data = stock)
## 
## Residuals:
##         1         2         3         4         5 
##  0.063847  0.062459 -0.040909 -0.007962 -0.077435 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  0.09382    0.09814   0.956    0.514
## Mac         -0.88124    1.10451  -0.798    0.571
## Sch          1.31506    1.98773   0.662    0.628
## Hali        -0.17174    1.34423  -0.128    0.919
## 
## Residual standard error: 0.1253 on 1 degrees of freedom
## Multiple R-squared:  0.6298, Adjusted R-squared:  -0.4809 
## F-statistic: 0.567 on 3 and 1 DF,  p-value: 0.7238</code></pre>
<pre class="r"><code>knitr::kable(summary(lm.stock)$coef,&quot;html&quot;,caption = &quot;summary table&quot;)</code></pre>
<table>
<caption>
<span id="tab:unnamed-chunk-1">Table 1: </span>summary table
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.0938234
</td>
<td style="text-align:right;">
0.0981405
</td>
<td style="text-align:right;">
0.9560112
</td>
<td style="text-align:right;">
0.5143146
</td>
</tr>
<tr>
<td style="text-align:left;">
Mac
</td>
<td style="text-align:right;">
-0.8812385
</td>
<td style="text-align:right;">
1.1045119
</td>
<td style="text-align:right;">
-0.7978533
</td>
<td style="text-align:right;">
0.5712808
</td>
</tr>
<tr>
<td style="text-align:left;">
Sch
</td>
<td style="text-align:right;">
1.3150576
</td>
<td style="text-align:right;">
1.9877281
</td>
<td style="text-align:right;">
0.6615883
</td>
<td style="text-align:right;">
0.6279094
</td>
</tr>
<tr>
<td style="text-align:left;">
Hali
</td>
<td style="text-align:right;">
-0.1717441
</td>
<td style="text-align:right;">
1.3442288
</td>
<td style="text-align:right;">
-0.1277641
</td>
<td style="text-align:right;">
0.9191012
</td>
</tr>
</tbody>
</table>
<p>The regression function is</p>
<p><span class="math display">\[Disney = 0.0938-0.8812\times MacDonalds   +1.3151\times Schlumberger-0.1717\times Haliburton\]</span></p>
<p>The <span class="math inline">\(R^2= 0.6298\)</span>, and the standard deviation of the residuals is <span class="math inline">\(\hat\sigma=0.1253\)</span>.</p>
<pre class="r"><code>newdata = data.frame(
  Mac=c(0.02604,0.07851,0.06732,-0.06483,-0.09029),
 Sch=c(0.02695,0.02362,0.23938,0.06127,-0.05773),
 Hali=c(0.00211,-0.04,0.35526,0.10714,-0.02933))
truevalue = c(0.1,0.06629,-0.11545,0.02008,-0.08268)
pre = predict(lm.stock,newdata,interval = &quot;prediction&quot;)
knitr::kable(pre,&quot;html&quot;,caption = &quot;predicted values and CI&quot;)</code></pre>
<table>
<caption>
<span id="tab:unnamed-chunk-2">Table 2: </span>predicted values and CI
</caption>
<thead>
<tr>
<th style="text-align:right;">
fit
</th>
<th style="text-align:right;">
lwr
</th>
<th style="text-align:right;">
upr
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.1059543
</td>
<td style="text-align:right;">
-1.799303
</td>
<td style="text-align:right;">
2.011211
</td>
</tr>
<tr>
<td style="text-align:right;">
0.0625688
</td>
<td style="text-align:right;">
-2.042785
</td>
<td style="text-align:right;">
2.167922
</td>
</tr>
<tr>
<td style="text-align:right;">
0.2882831
</td>
<td style="text-align:right;">
-3.186227
</td>
<td style="text-align:right;">
3.762793
</td>
</tr>
<tr>
<td style="text-align:right;">
0.2131270
</td>
<td style="text-align:right;">
-2.823438
</td>
<td style="text-align:right;">
3.249692
</td>
</tr>
<tr>
<td style="text-align:right;">
0.1025094
</td>
<td style="text-align:right;">
-3.055481
</td>
<td style="text-align:right;">
3.260500
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>pre_error = sd(pre[,1]-truevalue)
cat(&quot;The standard deviation of the prediction error is &quot;, pre_error,&quot;.&quot;)</code></pre>
<pre><code>## The standard deviation of the prediction error is  0.1670458 .</code></pre>
<div class="alert alert-warning">
  <p>对于这道题来讲，多元线性模型非常不显著，所以预测就没有太多意义了。这时，我们应该改进我们模型。比如，去掉不显著的项、添加高阶项或者交叉项。但注意，由于这个问题数据量为5，所以未知参数的个数不应该超过4，否则出现完全拟合的情况了。例如，下面的回归模型比之前的模型显著多了：</p>

</div>

<pre class="r"><code>lm.stock2 = lm(Disney~Sch+Mac+I(Sch*Mac),data=stock)##添加交叉项用I(Sch*Mac)表示
summary(lm.stock2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Disney ~ Sch + Mac + I(Sch * Mac), data = stock)
## 
## Residuals:
##         1         2         3         4         5 
## -0.001916  0.008816 -0.023597  0.003780  0.012917 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)   0.07869    0.02097   3.753    0.166
## Sch           0.44987    0.26008   1.730    0.334
## Mac          -1.06723    0.23295  -4.581    0.137
## I(Sch * Mac) 25.46566    5.92271   4.300    0.145
## 
## Residual standard error: 0.02862 on 1 degrees of freedom
## Multiple R-squared:  0.9807, Adjusted R-squared:  0.9228 
## F-statistic: 16.93 on 3 and 1 DF,  p-value: 0.1764</code></pre>
<pre class="r"><code>knitr::kable(summary(lm.stock2)$coef,&quot;html&quot;,caption = &quot;improved model&quot;)</code></pre>
<table>
<caption>
<span id="tab:unnamed-chunk-3">Table 3: </span>improved model
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.0786874
</td>
<td style="text-align:right;">
0.0209677
</td>
<td style="text-align:right;">
3.752788
</td>
<td style="text-align:right;">
0.1657869
</td>
</tr>
<tr>
<td style="text-align:left;">
Sch
</td>
<td style="text-align:right;">
0.4498716
</td>
<td style="text-align:right;">
0.2600825
</td>
<td style="text-align:right;">
1.729726
</td>
<td style="text-align:right;">
0.3337037
</td>
</tr>
<tr>
<td style="text-align:left;">
Mac
</td>
<td style="text-align:right;">
-1.0672273
</td>
<td style="text-align:right;">
0.2329468
</td>
<td style="text-align:right;">
-4.581420
</td>
<td style="text-align:right;">
0.1368111
</td>
</tr>
<tr>
<td style="text-align:left;">
I(Sch * Mac)
</td>
<td style="text-align:right;">
25.4656586
</td>
<td style="text-align:right;">
5.9227145
</td>
<td style="text-align:right;">
4.299660
</td>
<td style="text-align:right;">
0.1454766
</td>
</tr>
</tbody>
</table>
<div class="alert alert-warning">
  <p>在实际使用多元线性回归过程中，如何确定自变量和因变量之前的关系尤为重要。因为不是所有的自变量都可能用得上，而且可能出现非线性项（高阶项、交叉项）。这属于变量选择问题，也是线性回归中非常重要的主题。感兴趣的同学可以查阅课本208页。</p>

</div>


          </div>

          

        </div>

        <div class="body-footer">
          Last updated on Dec 18, 2018
        </div>

      </article>

      <footer class="site-footer">
  
  <p class="powered-by">
    <a href="/privacy/">Privacy Policy</a>
  </p>
  

  <p class="powered-by">
    Zhijian He &copy; 2018 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
  </p>
</footer>


    </main>
  </div>
</div>

    

    
    
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        CommonHTML: { linebreaks: { automatic: true } },
        tex2jax: { inlineMath: [ ['$', '$'], ['\\(','\\)'] ], displayMath: [ ['$$','$$'], ['\\[', '\\]'] ], processEscapes: false },
        TeX: { noUndefined: { attributes: { mathcolor: 'red', mathbackground: '#FFEEEE', mathsize: '90%' } } },
        messageStyle: 'none'
      });
    </script>
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha256-VsEqElsCHSGmnmHXGQzvoWjWwoznFSZc6hs7ARLRacQ=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
        
      

      
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_CHTML-full" integrity="sha256-GhM+5JHb6QUzOQPXSJLEWP7R73CbkisjzK5Eyij4U9w=" crossorigin="anonymous" async></script>
      
    

    <script src="/js/hugo-academic.js"></script>
    

    
    

    
    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "Search Results",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    <script src="/js/search.js"></script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

  </body>
</html>


