---
title: "第六次作业"
date: "2018-10-26"
categories: ["作业"]
Summary: "截止日期：2018-11-04 23:00"
tags: ["作业", "数理统计"]
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



True or false, and state why:

1. The significance level of a statistical test is equal to the probability that the
null hypothesis is true.
2. If the significance level of a test is decreased, the power of the test would be expected to
increase.
3. The probability that the null hypothesis is falsely rejected is equal to the power
of the test.
4. A type I error occurs when the test statistic falls in the rejection region of the
test.


---


A coin is thrown independently 10 times to test the hypothesis that the probability of heads is $1/2$ versus the alternative that the probability is not $1/2$. The test rejects
if either 0 or 10 heads are observed.

1. What is the significance level of the test?
2. If in fact the probability of heads is $0.1$, what is the power of the test?


---

Suppose that $X_1,X_2,X_3$ are samples of Bernoulli $B(1,p)$ population. For testing the hypothesis $H_0:p=1/2\ vs.\ H_1:p=3/4$, we use a rejection region:
$$W=\{(x_1,x_2,x_3):x_1+x_2+x_3\ge 2\}.$$

1. What are the probabilities of the two types of errors for $W$?
2. What is the power of the test? Graph the power as a function of $p$.


--- 





